. ~/.config/bash/aliases
. ~/.config/bash/shell_options
. ~/.config/bash/prompt

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

export FZF_DEFAULT_COMMAND='fd --type file'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export EDITOR=nvim
export PAGER=less
export DISPLAY=:0.0
umask 0022
